/**
 * The campaign domain.
 *
 * One idea holds the whole app together: a **campaign** belongs to an
 * **episode**, and fans out into **placements** — one row per platform, each
 * either organic (a post we publish) or paid (an ad we buy).
 *
 * Keeping organic and paid in the same table is the point. Richard does not
 * think "my Instagram post" and "my Instagram ad" as separate projects; he
 * thinks "this week's episode". Splitting them in the data model is what forces
 * people back into five browser tabs.
 */

export type Role = "owner" | "editor";

export type Platform =
  | "youtube"
  | "instagram"
  | "facebook"
  | "tiktok"
  | "x";

export type PlacementKind = "organic" | "paid";

export type CampaignStatus =
  | "draft"      // being built
  | "scheduled"  // approved, waiting for its start date
  | "active"     // running now
  | "done"       // finished
  | "paused";

export type PlacementStatus =
  | "draft"
  | "queued"     // approved here, not yet pushed out
  | "posted"     // organic: published
  | "live"       // paid: spending
  | "finished"
  | "failed";

export type Goal = "views" | "subscribers" | "attendance" | "awareness";

export interface Episode {
  id: string;
  number: number;
  title: string;
  guest: string | null;
  /** When it is recorded. */
  recorded_at: string | null;
  /** When it goes live on YouTube — the date every campaign is timed against. */
  publish_at: string;
  youtube_url: string | null;
  thumbnail_url: string | null;
  notes: string | null;
}

export interface Placement {
  id: string;
  campaign_id: string;
  platform: Platform;
  kind: PlacementKind;
  status: PlacementStatus;
  /** Paid only. Whole dollars — nobody budgets a podcast promo in cents. */
  budget: number | null;
  /** When this specific post/ad goes out. */
  run_at: string | null;
  copy: string;
  /** Image or vertical clip. Generated by the bot or uploaded. */
  creative_url: string | null;
  /** Set once the platform actually has it, so we can reconcile later. */
  external_id: string | null;
  /** Filled in after the fact. Null until the platform reports. */
  reach: number | null;
  clicks: number | null;
  spend: number | null;
}

export interface Campaign {
  id: string;
  episode_id: string;
  name: string;
  goal: Goal;
  status: CampaignStatus;
  budget_total: number;
  starts_at: string;
  ends_at: string;
  created_by: string | null;
  created_at: string;
}

export interface Connection {
  id: string;
  platform: Platform;
  /** An account can be connected for posting, for buying ads, or both. */
  kind: PlacementKind;
  account_name: string;
  connected: boolean;
  /** Why it is not usable, in plain Spanish, when connected is false. */
  blocked_reason: string | null;
  last_checked: string | null;
}

export interface Profile {
  id: string;
  full_name: string | null;
  role: Role;
  must_change_password: boolean;
}

/* ------------------------------------------------------------------ */
/* Presentation tables. Kept next to the types so a new platform is one
   edit, not a hunt through six switch statements.                     */
/* ------------------------------------------------------------------ */

export const PLATFORMS: Record<
  Platform,
  {
    label: string;
    short: string;
    color: string;
    organic: boolean;
    paid: boolean;
    /** Where the money is actually spent, which is not always the same brand. */
    adProduct: string;
  }
> = {
  youtube:   { label: "YouTube",   short: "YT", color: "#ff4444", organic: true, paid: true,  adProduct: "Google Ads" },
  instagram: { label: "Instagram", short: "IG", color: "#e1499a", organic: true, paid: true,  adProduct: "Meta Ads" },
  facebook:  { label: "Facebook",  short: "FB", color: "#4a8cff", organic: true, paid: true,  adProduct: "Meta Ads" },
  tiktok:    { label: "TikTok",    short: "TT", color: "#3ad9d1", organic: true, paid: true,  adProduct: "TikTok Ads / Promote" },
  x:         { label: "X",         short: "X",  color: "#c9c9d4", organic: true, paid: false, adProduct: "—" },
};

/**
 * Every account this console could use, whether or not a row exists for it.
 *
 * The connections page derives its list from here rather than from whatever
 * happens to be in the database. Rendering only existing rows meant a platform
 * with no row vanished from a page whose entire job is saying what is missing —
 * TikTok ads disappeared exactly that way.
 */
export function expectedConnections(): { platform: Platform; kind: PlacementKind }[] {
  const out: { platform: Platform; kind: PlacementKind }[] = [];
  for (const p of Object.keys(PLATFORMS) as Platform[]) {
    if (PLATFORMS[p].organic) out.push({ platform: p, kind: "organic" });
    if (PLATFORMS[p].paid) out.push({ platform: p, kind: "paid" });
  }
  return out;
}

export const GOALS: Record<Goal, { label: string; hint: string }> = {
  views:       { label: "Más vistas",       hint: "Que el episodio se vea. Lo normal cada semana." },
  subscribers: { label: "Más suscriptores", hint: "Crecer el canal, no solo un episodio." },
  attendance:  { label: "Llenar un evento", hint: "Cuando hay culto, invitado o algo presencial." },
  awareness:   { label: "Dar a conocer",    hint: "Gente nueva que nunca ha oído del programa." },
};

export const CAMPAIGN_STATUS: Record<
  CampaignStatus,
  { label: string; color: string }
> = {
  draft:     { label: "Borrador",  color: "var(--faint)" },
  scheduled: { label: "Programada", color: "var(--violet)" },
  active:    { label: "Activa",    color: "var(--green)" },
  paused:    { label: "Pausada",   color: "var(--amber)" },
  done:      { label: "Terminada", color: "var(--muted)" },
};

export const PLACEMENT_STATUS: Record<
  PlacementStatus,
  { label: string; color: string }
> = {
  draft:    { label: "Borrador",  color: "var(--faint)" },
  queued:   { label: "En cola",   color: "var(--violet)" },
  posted:   { label: "Publicado", color: "var(--green)" },
  live:     { label: "Al aire",   color: "var(--green)" },
  finished: { label: "Terminado", color: "var(--muted)" },
  failed:   { label: "Falló",     color: "var(--red)" },
};

/** Whole dollars, no cents — this is a podcast promo budget, not a ledger. */
export function money(n: number | null | undefined): string {
  if (n == null) return "—";
  return "$" + Math.round(n).toLocaleString("en-US");
}

export function count(n: number | null | undefined): string {
  if (n == null) return "—";
  if (n >= 1000000) return (n / 1000000).toFixed(1).replace(/\.0$/, "") + "M";
  if (n >= 1000) return (n / 1000).toFixed(1).replace(/\.0$/, "") + "K";
  return String(n);
}

/**
 * Parse a stored date.
 *
 * `new Date("2026-09-10")` is midnight **UTC**, which in New York renders as
 * the 9th — so a campaign starting the 10th displays as starting the day
 * before, everywhere a date-only column is shown. Date-only strings are built
 * from their parts instead, which makes them local midnight and keeps the
 * screen agreeing with the database.
 */
function parseDate(iso: string): Date {
  const dateOnly = /^(\d{4})-(\d{2})-(\d{2})$/.exec(iso);
  if (dateOnly) {
    return new Date(+dateOnly[1], +dateOnly[2] - 1, +dateOnly[3]);
  }
  return new Date(iso);
}

/** "12 de octubre" — the date format the owners actually read. */
export function shortDate(iso: string | null | undefined): string {
  if (!iso) return "—";
  const d = parseDate(iso);
  if (Number.isNaN(d.getTime())) return "—";
  return d.toLocaleDateString("es-DO", { day: "numeric", month: "long" });
}

export function daysUntil(iso: string | null | undefined): number | null {
  if (!iso) return null;
  const d = parseDate(iso);
  if (Number.isNaN(d.getTime())) return null;
  const ms = d.setHours(0, 0, 0, 0) - new Date().setHours(0, 0, 0, 0);
  return Math.round(ms / 86400000);
}
